# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_digital_window.ui'
#
# Created: Sat May  1 20:14:02 2010
#      by: PyQt5 UI code generator 4.6.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtWidgets, Qt

class Ui_DigitalWindow(object):
    def setupUi(self, DigitalWindow):
        DigitalWindow.setObjectName("DigitalWindow")
        DigitalWindow.resize(1236, 741)
        self.centralwidget = QtWidgets.QWidget(DigitalWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sinkFrame = QtWidgets.QFrame(self.centralwidget)
        self.sinkFrame.setMinimumSize(Qt.QSize(0, 550))
        self.sinkFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sinkFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sinkFrame.setObjectName("sinkFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.sinkFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sinkLayout = QtWidgets.QHBoxLayout()
        self.sinkLayout.setObjectName("sinkLayout")
        self.horizontalLayout_2.addLayout(self.sinkLayout)
        self.verticalLayout.addWidget(self.sinkFrame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sysBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sysBox.sizePolicy().hasHeightForWidth())
        self.sysBox.setSizePolicy(sizePolicy)
        self.sysBox.setMinimumSize(Qt.QSize(0, 0))
        self.sysBox.setMaximumSize(Qt.QSize(16777215, 120))
        self.sysBox.setAlignment(Qt.Qt.AlignLeading|Qt.Qt.AlignLeft|Qt.Qt.AlignTop)
        self.sysBox.setObjectName("sysBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sysBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sampleRateEdit = QtWidgets.QLineEdit(self.sysBox)
        self.sampleRateEdit.setMaximumSize(Qt.QSize(100, 16777215))
        self.sampleRateEdit.setObjectName("sampleRateEdit")
        self.gridLayout_2.addWidget(self.sampleRateEdit, 0, 3, 1, 1)
        self.sampleRateLabel = QtWidgets.QLabel(self.sysBox)
        self.sampleRateLabel.setObjectName("sampleRateLabel")
        self.gridLayout_2.addWidget(self.sampleRateLabel, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.sysBox)
        self.rxBox = QtWidgets.QGroupBox(self.centralwidget)
        self.rxBox.setMaximumSize(Qt.QSize(16777215, 120))
        self.rxBox.setAlignment(Qt.Qt.AlignLeading|Qt.Qt.AlignLeft|Qt.Qt.AlignTop)
        self.rxBox.setObjectName("rxBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.rxBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.alphaLabel = QtWidgets.QLabel(self.rxBox)
        self.alphaLabel.setObjectName("alphaLabel")
        self.gridLayout_3.addWidget(self.alphaLabel, 1, 0, 1, 1)
        self.alphaEdit = QtWidgets.QLineEdit(self.rxBox)
        self.alphaEdit.setMaximumSize(Qt.QSize(100, 16777215))
        self.alphaEdit.setObjectName("alphaEdit")
        self.gridLayout_3.addWidget(self.alphaEdit, 1, 1, 1, 1)
        self.gainMuLabel = QtWidgets.QLabel(self.rxBox)
        self.gainMuLabel.setObjectName("gainMuLabel")
        self.gridLayout_3.addWidget(self.gainMuLabel, 0, 0, 1, 1)
        self.gainMuEdit = QtWidgets.QLineEdit(self.rxBox)
        self.gainMuEdit.setMaximumSize(Qt.QSize(100, 16777215))
        self.gainMuEdit.setObjectName("gainMuEdit")
        self.gridLayout_3.addWidget(self.gainMuEdit, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.rxBox)
        self.channelModeBox = QtWidgets.QGroupBox(self.centralwidget)
        self.channelModeBox.setMaximumSize(Qt.QSize(16777215, 120))
        self.channelModeBox.setAlignment(Qt.Qt.AlignLeading|Qt.Qt.AlignLeft|Qt.Qt.AlignTop)
        self.channelModeBox.setObjectName("channelModeBox")
        self.gridLayout = QtWidgets.QGridLayout(self.channelModeBox)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.snrLabel = QtWidgets.QLabel(self.channelModeBox)
        self.snrLabel.setObjectName("snrLabel")
        self.gridLayout.addWidget(self.snrLabel, 0, 1, 1, 1)
        self.snrEdit = QtWidgets.QLineEdit(self.channelModeBox)
        self.snrEdit.setMaximumSize(Qt.QSize(100, 16777215))
        self.snrEdit.setObjectName("snrEdit")
        self.gridLayout.addWidget(self.snrEdit, 0, 2, 1, 1)
        self.freqLabel = QtWidgets.QLabel(self.channelModeBox)
        self.freqLabel.setObjectName("freqLabel")
        self.gridLayout.addWidget(self.freqLabel, 1, 1, 1, 1)
        self.freqEdit = QtWidgets.QLineEdit(self.channelModeBox)
        self.freqEdit.setMaximumSize(Qt.QSize(100, 16777215))
        self.freqEdit.setObjectName("freqEdit")
        self.gridLayout.addWidget(self.freqEdit, 1, 2, 1, 1)
        self.timeLabel = QtWidgets.QLabel(self.channelModeBox)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout.addWidget(self.timeLabel, 2, 1, 1, 1)
        self.timeEdit = QtWidgets.QLineEdit(self.channelModeBox)
        self.timeEdit.setMaximumSize(Qt.QSize(100, 16777215))
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout.addWidget(self.timeEdit, 2, 2, 1, 1)
        self.horizontalLayout.addWidget(self.channelModeBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pauseButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseButton.sizePolicy().hasHeightForWidth())
        self.pauseButton.setSizePolicy(sizePolicy)
        self.pauseButton.setMaximumSize(Qt.QSize(80, 16777215))
        self.pauseButton.setObjectName("pauseButton")
        self.verticalLayout_2.addWidget(self.pauseButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setMaximumSize(Qt.QSize(80, 16777215))
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout_2.addWidget(self.closeButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        DigitalWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DigitalWindow)
        self.menubar.setGeometry(Qt.QRect(0, 0, 1236, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        DigitalWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DigitalWindow)
        self.statusbar.setObjectName("statusbar")
        DigitalWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(DigitalWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(DigitalWindow)
        Qt.QObject.connect(self.closeButton, Qt.SIGNAL("clicked()"), DigitalWindow.close)
        Qt.QObject.connect(self.actionExit, Qt.SIGNAL("triggered()"), DigitalWindow.close)
        Qt.QMetaObject.connectSlotsByName(DigitalWindow)
        DigitalWindow.setTabOrder(self.snrEdit, self.freqEdit)
        DigitalWindow.setTabOrder(self.freqEdit, self.timeEdit)

    def retranslateUi(self, DigitalWindow):
        DigitalWindow.setWindowTitle(QtWidgets.QApplication.translate("DigitalWindow", "MainWindow", None, QtWidgets.QApplication.UnicodeUTF8))
        self.sysBox.setTitle(QtWidgets.QApplication.translate("DigitalWindow", "System Parameters", None, QtWidgets.QApplication.UnicodeUTF8))
        self.sampleRateLabel.setText(QtWidgets.QApplication.translate("DigitalWindow", "Sample Rate (sps)", None, QtWidgets.QApplication.UnicodeUTF8))
        self.rxBox.setTitle(QtWidgets.QApplication.translate("DigitalWindow", "Receiver Parameters", None, QtWidgets.QApplication.UnicodeUTF8))
        self.alphaLabel.setText(QtWidgets.QApplication.translate("DigitalWindow", "Alpha", None, QtWidgets.QApplication.UnicodeUTF8))
        self.gainMuLabel.setText(QtWidgets.QApplication.translate("DigitalWindow", "Gain mu", None, QtWidgets.QApplication.UnicodeUTF8))
        self.channelModeBox.setTitle(QtWidgets.QApplication.translate("DigitalWindow", "Channel Model Parameters", None, QtWidgets.QApplication.UnicodeUTF8))
        self.snrLabel.setText(QtWidgets.QApplication.translate("DigitalWindow", "SNR (dB)", None, QtWidgets.QApplication.UnicodeUTF8))
        self.freqLabel.setText(QtWidgets.QApplication.translate("DigitalWindow", "Frequency Offset (Hz)", None, QtWidgets.QApplication.UnicodeUTF8))
        self.timeLabel.setText(QtWidgets.QApplication.translate("DigitalWindow", "Timing Offset", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pauseButton.setText(QtWidgets.QApplication.translate("DigitalWindow", "Pause", None, QtWidgets.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtWidgets.QApplication.translate("DigitalWindow", "Close", None, QtWidgets.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("DigitalWindow", "&File", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtWidgets.QApplication.translate("DigitalWindow", "E&xit", None, QtWidgets.QApplication.UnicodeUTF8))

